### ISSUE TITLE
Result fine but variables and comments confusing in updateEligibleBalance()

### ISSUE THREAD

**Issue by t0bij** [hoprnet/hopr-farm#8]
[updateEligibleBalance()](https://github.com/hoprnet/hopr-farm/blob/41fb543aad7da97c9178ce49030bc463e1039097/contracts/HoprFarm.sol#L231) produces the right result but from my understanding the comments and variable names are highly misleading. The previous period is final and won’t be changed. The logic ensures that eligibleBalance and eligibleLiquidityPerPeriod will be reduced for the **current Period** if someone used closeFarm().

**Example:**
- we are in period 10
- currentBalance for account xyz is 200
- account xyz calls closeFarm(200)
- this results in a call of updateEligibleBalance(xyz [account],0 [newBalance],10 [currentPeriod])

**Analysis:**

Variable currentPeriod will be used as index for liquidityProviders and eligibleLiquidityPerPeriod. There, position 10 holds the values for period 11 and not 10. 

So actually, in the first if-block balanceFromLastPeriod is the balance from the current period 10 (Index 9). 

https://github.com/hoprnet/hopr-farm/blob/41fb543aad7da97c9178ce49030bc463e1039097/contracts/HoprFarm.sol#L233

If this is greater than newBalance closeFarm() must have been called. The removed funds aren’t eligible anymore and have to be removed from eligibleBalance for account xyz and eligibleLiquidityPerPeriod for the **current period**. This all happens but the comments and variables describe a different logic. Sorry for the novel. To make it even worse here are pictures for the example above. Column 1 is eligibleLiquidityPerPeriod Column 2 is eligibleBalance for account xyz.

**Before close():**

![before](https://user-images.githubusercontent.com/10200404/111131479-95291780-8578-11eb-8946-ed1986f78217.PNG)

**After close():**

![after](https://user-images.githubusercontent.com/10200404/111131639-bc7fe480-8578-11eb-8645-5cc7ace0d738.PNG)

The code which updates the upcoming periods is consequently also confusing regarding variable names. The iteration starts at index 10 which is named currentPeriod but actually holds the values for the next period 11.

https://github.com/hoprnet/hopr-farm/blob/41fb543aad7da97c9178ce49030bc463e1039097/contracts/HoprFarm.sol#L240

**Comment by QYuQianchen** [comment]
I see where it comes from. In light of your clear example with tables, here's a table that shows how those variables were intended to be used. 

Balance of liquidity tokens gets recorded per period. 0 refers to the time when incentive program is idle. However, only balance of the previous period is used for calculating rewards of the current period. E.g. balance put before the incentive program starts (before `distributionBlocks[0]`) can be counted into the reward of the 1st period.  

| index of `eligibleBalance` |       value of `currentPeriod`      | `eligibleBalance` is used for       |
|:--------------------------:|:-----------------------------------:|-------------------------------------|
|              0             | 0 (incentive program is not active) | calculating the reward of period 1  |
|              1             |                  1                  | calculating the reward of period 2  |
|              2             |                  2                  | calculating the reward of period 3  |
|              3             |                  3                  | calculating the reward of period 4  |
|              4             |                  4                  | calculating the reward of period 5  |
|              5             |                  5                  | calculating the reward of period 6  |
|              6             |                  6                  | calculating the reward of period 7  |
|              7             |                  7                  | calculating the reward of period 8  |
|              8             |                  8                  | calculating the reward of period 9  |
|              9             |                  9                  | calculating the reward of period 10 |
|             10             |                  10                 | calculating the reward of period 11 |
|             11             |                  11                 | calculating the reward of period 12 |
|             12             |                  12                 | calculating the reward of period 13 |
|             13             |                  13                 | --                                  |
|             14             |   14 (incentive program is closed)  | --                                  |

Actually, as tokens need to stay for at least one period to be eligible for any rewards, iterations in [updateEligibleBalance](https://github.com/hoprnet/hopr-farm/blob/41fb543aad7da97c9178ce49030bc463e1039097/contracts/HoprFarm.sol#L240) and [_openFarm](https://github.com/hoprnet/hopr-farm/blob/41fb543aad7da97c9178ce49030bc463e1039097/contracts/HoprFarm.sol#L255) can use `<` instead of `<=`

**Comment by t0bij** [comment]
Yes, that fits my understanding of the variables. For me it's just not clear from the names and comments. I only understood the calculation after trying it out. But the result is OK.

I agree regarding https://github.com/hoprnet/hopr-farm/blob/41fb543aad7da97c9178ce49030bc463e1039097/contracts/HoprFarm.sol#L255 with "<=" here it's possible to open a farm during period 13 which will never have any benefit for the user. I saw it too and opened a bug with low severity on immunefi.

I also agree on https://github.com/hoprnet/hopr-farm/blob/41fb543aad7da97c9178ce49030bc463e1039097/contracts/HoprFarm.sol#L240 I don't see any negative effect but it's cleaner to use "<" here, too.
